apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: China
  name: ${SERVER_NAME}
  namespace: ${NAMESPACE}
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubesphere.io/description: ${ROLE_NAME}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVER_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${SERVER_NAME}
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-6r042a
          persistentVolumeClaim:
            claimName: ${NAMESPACE}
      containers:
        - name: ${SERVER_NAME}
          image: ${REGISTRY}/${NAMESPACE}/channel:${IMAGE_TAG}
          imagePullPolicy: Always
          command: ["ls","test.txt"]
          ports:
            - containerPort: ${CONTAINER_PORT}
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 1
              memory: 1024Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-6r042a
              mountPath: /home/
          livenessProbe:
            exec:
              command:
                - ls
                - /home/code/toa_install.sh
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
