apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ${NAMESPACE}
  namespace: ${NAMESPACE}
  labels:
    pv: ${NAMESPACE}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /www/${NAMESPACE}/conf
    server: ${NFS_SERVER}
