apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NAMESPACE}
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv: ${NAMESPACE}
